language: c

os:
  - linux

sudo: false

addons:
  firefox: latest

env:
  global:
    - GECKODRIVER_VERSION=0.20.0
    - GECKODRIVER_DIST=geckodriver-v0.20.0-linux64.tar.gz
    - MINICONDA_DIST=Miniconda3-4.4.10-Linux-x86_64.sh
    - CONDA_DIR=$HOME/miniconda3
    - PATH=$CONDA_DIR/bin:$PATH

cache:
  directories:
    - $HOME/.cache/stuff

before_install:
  - mkdir -p $HOME/.cache/stuff
  - cd $HOME/.cache/stuff && wget --no-verbose -N https://repo.continuum.io/miniconda/${MINICONDA_DIST}
  - cd $HOME/.cache/stuff && wget --no-verbose -N https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/${GECKODRIVER_DIST}
  - bash $HOME/.cache/stuff/${MINICONDA_DIST} -b -p $CONDA_DIR
  - tar -xaf $HOME/.cache/stuff/${GECKODRIVER_DIST} -C $CONDA_DIR/bin/

install:
  - conda env update -n base --file environment.yml
  - source activate base && bash postBuild

script:
   - ls
   - echo hooray
