language: c

os: linux

sudo: required

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - MINICONDA_DIST=Miniconda3-4.5.4-Linux-x86_64.sh
    - MINICONDA_SOURCE=https://repo.continuum.io/miniconda
    - CONDA_DIR=$HOME/miniconda3
    - PATH=$CONDA_DIR/bin:$PATH

before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
script: ./scripts/travis/test.sh
after_failure: ./scripts/travis/after_failure.sh
before_deploy: ./scripts/travis/before_deploy.sh

deploy:
  provider: pages
  local-dir: demo
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
