#!/bin/bash
# This is used by repo2docker _after_ environment.yml, but still during the
# docker build, which is simpler than a dedicated Dockerfile
set -ex
jlpm
jlpm lerna bootstrap
jlpm lerna build
jlpm lerna link
jupyter lab build
